added new CreateConnection class
TIS2022-FMFI/web-backups pull request #60
Opened 2022-12-05 13:53 UTC by M4jo

Added new class that creates a connection to a remote server

2022-12-05 14:25 UTC, arti1221 requested changes
Please remove pvsm

2022-12-05 14:25 UTC, arti1221 commented on src/web_backups/main/ui/createConnection/CreateConnection.java
> +    public static void main(String[] args) {
This should be removed as the application is being started from a different class.

2022-12-05 14:25 UTC, arti1221 commented on src/web_backups/main/ui/createConnection/CreateConnection.java
> +        String username = "webbackup";
All attributes should be declared via constructor. Please make sure to make these attributes private.

2022-12-05 14:25 UTC, arti1221 commented on src/web_backups/main/ui/createConnection/CreateConnection.java
> +package web_backups.main.ui.createConnection;
This should be moved to a different package as it is not a UI functionality but making a connection to site specified in config. file. Please move this into global library.

2022-12-05 14:25 UTC, arti1221 commented on src/web_backups/main/ui/createConnection/CreateConnection.java
> +        } catch (JSchException e) {
Please add a validation message for the user. Use NoValidDataException.java instead.

2022-12-05 14:25 UTC, arti1221 commented on src/web_backups/main/ui/createConnection/CreateConnection.java
> +package web_backups.main.ui.createConnection;
Please add Jsch package to libraries as it is not a default java package.

2022-12-13 08:30 UTC, Yarvelian approved these changes
Nice

2023-02-06 19:50 UTC, closed without merging